"""Equity (S1-S7) market-condition entry gates / exits / ``--search-sl-loosen`` (docs/strategy_
research/atr_grid/atr_grid_2027_design.md section 5, the goal2027atr grid). The deferral in
``docs/plans/2026-09-15-option-market-condition-genes-impl.md`` Task 11 ("do not change strategy
s1 s7") was explicitly lifted by the operator on 2026-09-29 for THIS grid only, behind the flags
this module pins.

What this pins, in the order the failures would bite:

* with NO new flags, every S1-S7 builder is byte-identical to the pre-lift code -- compared
  directly against ``git show dbb071d0:testplatform/ba2test_launcher.py`` (the commit this
  worktree branched from), not a hand-maintained literal, so the pin cannot silently drift from
  what "before this change" actually built.
* with a profile on, every S1-S7 strategy collects exactly 15 more genes (6 ohlcv-v1 + 9
  ta-structure-v1, the same registry-driven count the option builders already pin), all on the
  INITIAL-ENTRY tree(s), and S1's three conviction tiers SHARE one 15-gene set (not 45).
* ``--market-exit`` appends the templates after the existing exits (before a terminal catch-all,
  which would otherwise shadow them), passes ``assert_market_rule_actions``, and reports the real
  gene count per strategy (7 when the strategy's floor stop swallows the market stop rule, 9 for
  S6 which has no floor-stop catch-all at all).
* ``--market-condition-mode all-off`` is byte-identical to profile ``none`` for both the entry
  gates and the exits (the matched control, design section 6).
* ``--search-sl-loosen`` adds exactly one ``model:*`` gene, decodes through
  ``_build_daily_trial_config`` and reads back as a real bool via ``coerce_bool``, and is refused
  on a bypass expert.
* an equity job whose universe the pinned manifest does not cover fails before dispatch, naming
  the missing symbols -- the SAME generic check the option path already had
  (``_apply_market_conditions``/``check_market_condition_coverage``), now reachable for S1-S7
  because they are in ``_MARKET_CONDITION_STRATEGIES``.
"""
from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from datetime import date

import pytest

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # testplatform/backend
_LAUNCHER = os.path.normpath(os.path.join(_ROOT, "..", "ba2test_launcher.py"))
_BASE_COMMIT = "dbb071d0"  # the commit this worktree (feat/atr27-equity-mktcond) branched from
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from app.services.strategy_param_space import collect_param_space  # noqa: E402
from ba2_common.core.interfaces.ExtendableSettingsInterface import coerce_bool  # noqa: E402
from ba2_common.core.market_conditions import PROFILES  # noqa: E402

_spec = importlib.util.spec_from_file_location("ba2test_launcher_eqmc", _LAUNCHER)
mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mod)

EQUITY = ["S1", "S2", "S3", "S4", "S5", "S6", "S7"]
BOTH_PROFILES = ("ohlcv-v1", "ta-structure-v1")


def _pristine_module():
    """The launcher AS THE BASE COMMIT BUILT IT, loaded from a git blob (never regenerated by
    hand): ``git show <commit>:<path>`` piped to a throwaway file, loaded exactly like
    ``test_launcher_market_condition_profile.py``'s hand-copied JSON literals were originally
    produced -- except this stays correct automatically, because it re-reads the commit instead
    of a snapshot someone typed out."""
    repo_root = os.path.normpath(os.path.join(_ROOT, "..", ".."))
    blob = subprocess.run(
        ["git", "show", f"{_BASE_COMMIT}:testplatform/ba2test_launcher.py"],
        cwd=repo_root, capture_output=True, check=True, text=True,
    ).stdout
    import tempfile
    fd, path = tempfile.mkstemp(suffix="_ba2test_launcher_pristine.py")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(blob)
    spec = importlib.util.spec_from_file_location("ba2test_launcher_eqmc_pristine", path)
    pristine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(pristine)
    return pristine


@pytest.fixture(scope="module")
def pristine():
    return _pristine_module()


@pytest.fixture(autouse=True)
def _reset_globals():
    """Every module global the equity market-condition flags touch, reset before AND after each
    test -- these are module-level, so a test that forgets to restore one would leak into every
    test collected after it (the option test file's ``profile_on`` fixture is the same idiom)."""
    def _off():
        mod._MARKET_CONDITION_PROFILES = ()
        mod._MARKET_CONDITION_MANIFESTS = {}
        mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_SEARCHED
        mod._MARKET_EXIT_KINDS_SELECTED = ()
        mod._SEARCH_SL_LOOSEN = False
    _off()
    yield
    _off()


def _market_ids(node) -> list:
    out: list = []

    def walk(n):
        if isinstance(n, list):
            for x in n:
                walk(x)
            return
        if not isinstance(n, dict):
            return
        cid = n.get("id")
        if isinstance(cid, str) and "-market-" in cid:
            out.append(cid)
        for v in n.values():
            walk(v)

    walk(node)
    return out


# --------------------------------------------------------------------------- byte identity
@pytest.mark.parametrize("kind", EQUITY)
def test_no_flags_reproduces_the_pre_lift_builder_byte_for_byte(kind, pristine):
    """The hard constraint: with no new flags, every S1-S7 builder is untouched."""
    assert mod._MARKET_CONDITION_PROFILES == ()
    assert mod._MARKET_CONDITION_MODE == mod._MARKET_CONDITION_MODE_SEARCHED
    assert mod._MARKET_EXIT_KINDS_SELECTED == ()
    current = mod._build_strategy(kind, f"pin-{kind}", "FMPRating")
    before = pristine._build_strategy(kind, f"pin-{kind}", "FMPRating")
    assert current.entry_rules == before.entry_rules, kind
    assert current.exit_rules == before.exit_rules, kind


def test_the_equity_keys_are_in_the_permitted_market_condition_set():
    assert mod._EQUITY_MARKET_CONDITION_STRATEGIES == set(EQUITY)
    assert mod._EQUITY_MARKET_CONDITION_STRATEGIES <= mod._MARKET_CONDITION_STRATEGIES
    # O_STK still has no entry gate of its own -- unaffected by the equity lift.
    assert "O_STK" not in mod._MARKET_CONDITION_STRATEGIES


# --------------------------------------------------------------------------- entry gate genes
@pytest.mark.parametrize("kind", EQUITY)
def test_each_strategy_collects_exactly_fifteen_more_genes_with_both_profiles(kind):
    """6 (ohlcv-v1) + 9 (ta-structure-v1) = 15 -- verified against the registry, not restated:
    the searched-field counts come straight from PROFILES, so a registry change moves this
    number instead of silently invalidating it."""
    ohlcv_searched = len([f for f in PROFILES["ohlcv-v1"].fields if f.searched])
    ta_searched = len([f for f in PROFILES["ta-structure-v1"].fields if f.searched])
    ta_numeric = len([f for f in PROFILES["ta-structure-v1"].fields
                      if f.searched and f.kind == "numeric"])
    ta_categorical = ta_searched - ta_numeric
    expected = 2 * ohlcv_searched + 2 * ta_numeric + ta_categorical
    assert expected == 15, "design section 5.1's '6 + 9 = 15' -- report if the registry moved it"

    mod._MARKET_CONDITION_PROFILES = BOTH_PROFILES
    strat = mod._build_strategy(kind, f"g-{kind}", "FMPRating")
    genes = sorted(g for g in collect_param_space(strat) if "-market-" in g)
    assert len(genes) == expected, (kind, genes)


@pytest.mark.parametrize("kind", EQUITY)
def test_the_gates_sit_only_on_initial_entry_trees_never_on_an_exit_rule(kind):
    mod._MARKET_CONDITION_PROFILES = BOTH_PROFILES
    strat = mod._build_strategy(kind, f"t-{kind}", "FMPRating")
    entry_ids = _market_ids(strat.entry_rules)
    assert entry_ids, kind
    assert _market_ids(strat.exit_rules) == [], kind
    # Every entry rule that HAS a condition tree carries the gates (S1's 3 tiers; every other
    # kind's single entry rule) -- none is left ungated.
    trees = [r for r in strat.entry_rules if isinstance(r.get("conditions"), dict)
             and r["conditions"].get("conditions")]
    for rule in trees:
        assert set(_market_ids(rule["conditions"])) == {
            f"{kind.lower()}-market-{s}" for s in
            ("slope", "adx", "rv", "dist-support", "dist-resistance", "chan-pos",
             "vs-prior-high", "structure")}


def test_s1s_three_tiers_share_one_gate_set_not_three():
    """Design D5: the three conviction tiers must carry the SAME 15 genes, not 45 -- proven by
    id identity (the sharing mechanism IS shared leaf ids, see
    ``_append_equity_market_condition_gates``'s docstring) and by the collected gene count."""
    mod._MARKET_CONDITION_PROFILES = BOTH_PROFILES
    strat = mod._build_strategy("S1", "s1-share", "FMPRating")
    assert len(strat.entry_rules) == 3
    per_tier_ids = [sorted(_market_ids(r["conditions"])) for r in strat.entry_rules]
    assert per_tier_ids[0] == per_tier_ids[1] == per_tier_ids[2]
    assert len(per_tier_ids[0]) == 8            # 3 ohlcv + 5 ta-structure leaves
    genes = [g for g in collect_param_space(strat) if "-market-" in g]
    assert len(genes) == 15, "shared ids collapse 3x8 leaves into 15 genes, not 45"


def test_no_flags_adds_no_market_gene_to_any_equity_strategy():
    for kind in EQUITY:
        strat = mod._build_strategy(kind, f"n-{kind}", "FMPRating")
        assert _market_ids(strat.entry_rules) == [], kind
        assert _market_ids(strat.exit_rules) == [], kind
        assert [g for g in collect_param_space(strat) if "-market-" in g] == [], kind


# --------------------------------------------------------------------------- --market-exit
#: Per-strategy expected (rule ids, gene count) with --market-exit exit,stop,tp and both
#: profiles. S1-S5/S7 have a terminal catch-all floor stop that itself adjusts the stop-loss, so
#: the STOP rule is omitted (7 genes); S6 has no catch-all at all, so all four rules attach
#: (9 genes). Measured directly against the built strategies, not asserted from a formula, since
#: the omission depends on each strategy's own exit shape.
_EXPECTED_MARKET_EXIT_GENES = {
    "S1": 7, "S2": 7, "S3": 7, "S4": 7, "S5": 7, "S6": 9, "S7": 7,
}


@pytest.mark.parametrize("kind", EQUITY)
def test_market_exit_appends_after_the_existing_exits_and_passes_the_action_guard(kind):
    from ba2_common.core.market_condition_rules import assert_market_rule_actions

    plain = mod._build_strategy(kind, f"me-plain-{kind}", "FMPRating")   # defaults: no market exit

    mod._MARKET_CONDITION_PROFILES = BOTH_PROFILES
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_SEARCHED
    mod._MARKET_EXIT_KINDS_SELECTED = ("exit", "stop", "tp")
    gated = mod._build_strategy(kind, f"me-gated-{kind}", "FMPRating")

    plain_ids = [r["id"] for r in plain.exit_rules]
    gated_ids = [r["id"] for r in gated.exit_rules]
    mkt_ids = [i for i in gated_ids if "-mkt-" in i]
    assert mkt_ids, kind
    # every ORIGINAL exit rule is still present, in its original relative order
    assert [i for i in gated_ids if i not in mkt_ids] == plain_ids, kind
    # market rules appended after every original exit that precedes them
    first_mkt = gated_ids.index(mkt_ids[0])
    assert set(gated_ids[:first_mkt]) <= set(plain_ids), kind

    assert_market_rule_actions(gated.exit_rules, f"{kind} exit rules")  # no exception = pass

    # Every market-exit gene's id (rule enable, leaf value, action value) is built from one of
    # the market rule ids, and no OTHER gene in these strategies ever contains "-mkt-" -- so this
    # is an exact, not a heuristic, count.
    all_genes = collect_param_space(gated)
    mkt_genes = sorted(g for g in all_genes if "-mkt-" in g)
    assert len(mkt_genes) == _EXPECTED_MARKET_EXIT_GENES[kind], (kind, mkt_genes)


def test_market_exit_is_refused_for_a_non_equity_kind():
    """--market-exit is attached only by the equity dispatch; an option kind would otherwise
    silently build without the requested rules while the command line claims they are on."""
    mod._MARKET_CONDITION_PROFILES = ("ohlcv-v1",)
    mod._MARKET_EXIT_KINDS_SELECTED = ("exit",)
    with pytest.raises(SystemExit, match="equity-only"):
        mod._apply_market_conditions(
            "optimize", {"enabled_instruments": ["AAA"], "start_date": "2025-06-30",
                         "end_date": "2025-07-01"}, mod._build_strategy("S1", "x", "FMPRating"),
            "O_LC")


def test_market_exit_requires_profile_and_the_searched_mode():
    with pytest.raises(SystemExit, match="requires --market-condition-profile"):
        mod._resolve_market_exit_kinds("exit", "optimize")
    mod._MARKET_CONDITION_PROFILES = ("ohlcv-v1",)
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_ALL_OFF
    with pytest.raises(SystemExit, match="cannot carry them"):
        mod._resolve_market_exit_kinds("exit", "optimize")
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_SEARCHED
    assert mod._resolve_market_exit_kinds("tp,exit", "optimize") == ("exit", "tp")
    assert mod._resolve_market_exit_kinds(None, "optimize") == ()
    with pytest.raises(SystemExit, match="distinct kinds"):
        mod._resolve_market_exit_kinds("exit,bogus", "optimize")


# --------------------------------------------------------------------------- all-off control
@pytest.mark.parametrize("kind", EQUITY)
def test_all_off_mode_is_byte_identical_to_no_profile_for_gates_and_exits(kind):
    plain = mod._build_strategy(kind, f"ao-plain-{kind}", "FMPRating")

    mod._MARKET_CONDITION_PROFILES = BOTH_PROFILES
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_ALL_OFF
    mod._MARKET_EXIT_KINDS_SELECTED = ()   # --market-exit cannot combine with all-off (refused)
    alloff = mod._build_strategy(kind, f"ao-plain-{kind}", "FMPRating")

    assert alloff.entry_rules == plain.entry_rules, kind
    assert alloff.exit_rules == plain.exit_rules, kind
    assert [g for g in collect_param_space(alloff) if "-market-" in g] == [], kind


def test_market_condition_mode_flag_defaults_and_validates():
    import argparse

    p = argparse.ArgumentParser()
    mod._add_market_condition_args(p)
    args = p.parse_args([])
    assert args.market_condition_mode == "searched"
    assert mod._resolve_market_condition_mode(None, "optimize") == "searched"
    assert mod._resolve_market_condition_mode("all-off", "optimize") == "all-off"
    with pytest.raises(SystemExit, match="must be"):
        mod._resolve_market_condition_mode("bogus", "optimize")
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_SEARCHED


# --------------------------------------------------------------------------- --search-sl-loosen
def test_search_sl_loosen_adds_exactly_one_gene():
    assert mod._sl_loosen_gene_space() == {}
    mod._resolve_search_sl_loosen(True, "optimize")
    space = mod._sl_loosen_gene_space()
    assert list(space) == ["allow_ruleset_sl_loosen"]
    assert space["allow_ruleset_sl_loosen"] == {
        "optimize": True, "min": 0, "max": 1, "step": 1, "type": "int"}


def test_search_sl_loosen_decodes_to_a_real_bool_through_the_trial_config():
    """Through ``_build_daily_trial_config`` -- the settings whitelist trap (memory
    'reference-trial-config-whitelist-drops-new-knobs'): confirms the key is NOT dropped, since
    that path merges ``expert_overrides`` onto the per-trial settings UNCONDITIONALLY (no
    per-key whitelist), and that whatever lands there reads back as a real bool via
    ``coerce_bool`` -- the "1"-string trap the option grid's ``use_atr_stop`` fell into before."""
    from app.services.strategy_optimization_handler import _build_daily_trial_config

    backtest_cfg = {
        "backtest_id": "sl", "start_date": "2024-01-01", "end_date": "2024-02-01",
        "enabled_instruments": ["AAA"], "experts": [{"class": "FMPRating", "settings": {}}],
        "initial_capital": 20_000.0, "account_settings": {}, "warmup_days": 0, "seed": 1,
    }
    for raw, expected in ((1, True), (0, False), ("1", True)):
        decoded = {"expert_overrides": {"allow_ruleset_sl_loosen": raw},
                  "entry_rules": [], "exit_rules": []}
        trial = _build_daily_trial_config(backtest_cfg, decoded, None, option_trade_records=False)
        stored = trial["experts"][0]["settings"]["allow_ruleset_sl_loosen"]
        assert coerce_bool(stored) is expected, (raw, stored)


def test_search_sl_loosen_is_refused_on_a_bypass_expert():
    mod._SEARCH_SL_LOOSEN = True
    with pytest.raises(SystemExit, match="bypass expert"):
        mod._refuse_sl_loosen_on_bypass("optimize", "FACTOR", True)
    mod._refuse_sl_loosen_on_bypass("optimize", "S1", False)  # no raise: not bypass
    mod._SEARCH_SL_LOOSEN = False
    mod._refuse_sl_loosen_on_bypass("optimize", "FACTOR", True)  # no raise: flag not set


def test_search_sl_loosen_is_searched_in_both_arms_design_d6():
    """The gene space helper does not consult ``_MARKET_CONDITION_MODE`` at all -- design D6
    requires the control to carry it too, or the comparison would measure two variables."""
    mod._resolve_search_sl_loosen(True, "optimize")
    for target_mode in (mod._MARKET_CONDITION_MODE_SEARCHED, mod._MARKET_CONDITION_MODE_ALL_OFF):
        mod._MARKET_CONDITION_MODE = target_mode
        assert list(mod._sl_loosen_gene_space()) == ["allow_ruleset_sl_loosen"]
    mod._MARKET_CONDITION_MODE = mod._MARKET_CONDITION_MODE_SEARCHED


# --------------------------------------------------------------------------- missing-coverage
def _publish_ohlcv_manifest(root, symbols=("AAA", "BBB")):
    from ba2_common.core.market_condition_store import MarketConditionStore
    from ba2_common.core.market_conditions import PROFILES as _P, STATUS_INSUFFICIENT_HISTORY

    profile = _P["ohlcv-v1"]
    fields = [f.name for f in profile.fields]
    sessions = [date(2025, 6, 27), date(2025, 6, 30), date(2025, 7, 1)]
    store = MarketConditionStore(root)
    objects = []
    for symbol in symbols:
        rows = [{"session": s, "values": [None] * len(fields),
                 "status": [STATUS_INSUFFICIENT_HISTORY] * len(fields),
                 "reasons": ["published row"] * len(fields),
                 "window_digest": "sha256:" + "0" * 64, "raw_shard_ref": "",
                 "raw_row_lo": 0, "raw_row_hi": 0} for s in sessions]
        for month in sorted({(r["session"].year, r["session"].month) for r in rows}):
            entry, _ = store.write_feature_object(
                profile, symbol, [r for r in rows if (r["session"].year, r["session"].month) == month])
            objects.append(entry)
    manifest = store.make_manifest(
        profile, source_profile="fmp-daily-split-adjusted-v1", timing_policy="prior_session_v1",
        objects=objects, raw_objects=[],
        coverage={s: {"rows": len(sessions)} for s in symbols}, universe=list(symbols),
        sessions=sessions, window_start=date(2025, 6, 30), window_end=date(2025, 7, 1))
    return store, store.write_manifest(manifest)


@pytest.fixture
def equity_snapshot(tmp_path, monkeypatch):
    import ba2_common.config as bc

    store, digest = _publish_ohlcv_manifest(tmp_path / "cache")
    monkeypatch.setattr(bc, "CACHE_FOLDER", str(store.cache_root))
    return digest


def test_an_equity_job_with_symbols_missing_from_the_manifest_fails_before_dispatch(
        equity_snapshot):
    """Requirement 6: the equity path re-uses the option path's coverage guard verbatim, now
    reachable because S1-S7 are in _MARKET_CONDITION_STRATEGIES. FAILS LOUD, naming the missing
    symbols, before any trial is dispatched."""
    mod._MARKET_CONDITION_PROFILES = ("ohlcv-v1",)
    mod._MARKET_CONDITION_MANIFESTS = {"ohlcv-v1": equity_snapshot}
    strat = mod._build_strategy("S2", "cov-S2", "FMPRating")
    block = {"enabled_instruments": ["AAA", "ZZZ", "QQQ"], "start_date": "2025-06-30",
            "end_date": "2025-07-01", "experts": [{"class": "FMPRating", "settings": {}}]}
    with pytest.raises(SystemExit) as e:
        mod._apply_market_conditions("optimize", block, strat, "S2")
    message = str(e.value)
    assert "ZZZ" in message and "QQQ" in message
    assert "does not cover" in message
    assert "market_condition_profiles" not in block   # refused BEFORE any write


def test_an_equity_job_with_full_coverage_is_accepted(equity_snapshot):
    mod._MARKET_CONDITION_PROFILES = ("ohlcv-v1",)
    mod._MARKET_CONDITION_MANIFESTS = {"ohlcv-v1": equity_snapshot}
    strat = mod._build_strategy("S2", "cov-ok-S2", "FMPRating")
    block = {"enabled_instruments": ["AAA", "BBB"], "start_date": "2025-06-30",
            "end_date": "2025-07-01", "experts": [{"class": "FMPRating", "settings": {}}]}
    recorded = mod._apply_market_conditions("optimize", block, strat, "S2")
    assert recorded["profiles"] == ["ohlcv-v1"]
    assert block["experts"][0]["settings"]["market_condition_profile"] == "ohlcv-v1"


# --------------------------------------------------------------------------- driver passthrough
_DRIVER = os.path.normpath(os.path.join(_ROOT, "..", "..", "tools",
                                        "run_screener_capband_matrix.py"))


@pytest.fixture(scope="module")
def driver():
    spec = importlib.util.spec_from_file_location("run_screener_capband_matrix_eqmc", _DRIVER)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _args(driver, **overrides):
    defaults = dict(market_condition_profile=None, market_condition_manifest=None,
                    market_exit=None, market_condition_mode=None, search_sl_loosen=False)
    defaults.update(overrides)
    import argparse
    return argparse.Namespace(**defaults)


def test_driver_forwards_nothing_with_no_flags(driver):
    assert driver.market_condition_passthrough(_args(driver)) == []
    assert driver.market_condition_passthrough(_args(driver, market_condition_mode="searched")) == []


def test_driver_forwards_each_flag_only_when_given(driver):
    assert driver.market_condition_passthrough(_args(
        driver, market_condition_profile="ohlcv-v1,ta-structure-v1")) == [
        "--market-condition-profile", "ohlcv-v1,ta-structure-v1"]
    assert driver.market_condition_passthrough(_args(
        driver, market_condition_manifest="abc123")) == ["--market-condition-manifest", "abc123"]
    assert driver.market_condition_passthrough(_args(
        driver, market_exit="exit,stop,tp")) == ["--market-exit", "exit,stop,tp"]
    assert driver.market_condition_passthrough(_args(
        driver, market_condition_mode="all-off")) == ["--market-condition-mode", "all-off"]
    assert driver.market_condition_passthrough(_args(
        driver, search_sl_loosen=True)) == ["--search-sl-loosen"]


def test_driver_digest_changes_identity_only_when_content_changes(driver):
    base_cmd = ["exe", "optimize", "--expert", "FMPRating", "--universe", "AAPL",
               "--start", "2020-01-01", "--end", "2025-01-01", "--name", "job1",
               "--parallel", "4"]
    name_a = driver._job_name("job1", base_cmd)
    # --name/--parallel/--workers must NOT move the digest
    cmd_diff_name_only = list(base_cmd)
    cmd_diff_name_only[cmd_diff_name_only.index("--parallel") + 1] = "16"
    assert driver._job_name("job1", cmd_diff_name_only) == name_a
    with_workers = base_cmd + ["--workers", "remote227"]
    assert driver._job_name("job1", with_workers) == name_a
    # any other token DOES move the digest
    cmd_with_flag = base_cmd + ["--market-condition-profile", "ohlcv-v1"]
    name_b = driver._job_name("job1", cmd_with_flag)
    assert name_b != name_a
    assert name_b.startswith("job1-d")
    # deterministic
    assert driver._job_name("job1", cmd_with_flag) == name_b


def test_driver_dry_run_is_unaffected_with_no_new_flags():
    """The hard constraint at the driver level: an invocation with none of the five flags prints
    the SAME job names/order as before this change (no digest token anywhere)."""
    import re

    # The decision-time gene is DEFAULT ON for this driver since 2026-10-07 (its own digest +
    # '-timegene' token); `--decision-times fixed` is the legacy invocation this test pins.
    result = subprocess.run(
        [sys.executable, _DRIVER, "--strategies", "S1,S6", "--bands", "large", "--dry-run",
         "--decision-times", "fixed"],
        capture_output=True, text=True, cwd=os.path.normpath(os.path.join(_ROOT, "..", "..")),
    )
    assert result.returncode == 0, result.stderr
    assert not re.search(r"-d[0-9a-f]{12}\b", result.stdout)  # no digest token anywhere
    assert "scr-large-FMPRating-S1-from2022" in result.stdout
    assert "scr-large-FMPRating-S6-from2022" in result.stdout


def test_driver_dry_run_default_carries_the_decision_time_gene_in_every_classic_name():
    import re

    result = subprocess.run(
        [sys.executable, _DRIVER, "--strategies", "S1", "--bands", "large", "--dry-run"],
        capture_output=True, text=True, cwd=os.path.normpath(os.path.join(_ROOT, "..", "..")),
    )
    assert result.returncode == 0, result.stderr
    assert "decision times (GA gene schedule:time): 09:35,09:40,09:45,10:00,12:00,15:30,15:45" \
        in result.stdout
    assert re.search(r"scr-large-FMPRating-S1-from2022-timegene-sup1-lds1-d[0-9a-f]{12}", result.stdout)
    # the bypass FactorRanker job keeps its plain name: it has no schedule genes
    assert re.search(r"(TODO|DONE)\s+scr-large-FactorRanker-sup1\s", result.stdout)



def test_search_sl_loosen_gene_reaches_the_trial_setting_end_to_end():
    """The gene name must survive collect_param_space -> decode_params as the REAL setting name.

    2026-10-02: the gene was keyed ``model:allow_ruleset_sl_loosen`` and collected as
    ``model:model:...``, so decode produced an override nothing reads and the gene was inert in
    every goal2027atr job. The test above fed ``decode`` the right key by hand, which hid it."""
    from app.services.strategy_param_space import collect_param_space, decode_params
    from app.services.strategy_optimization_handler import _build_daily_trial_config

    mod._resolve_search_sl_loosen(True, "optimize")
    strategy = mod._build_strategy("S6", "sl-e2e", "FMPRating")
    space = collect_param_space(strategy, expert_cfg=mod._sl_loosen_gene_space())
    assert "model:allow_ruleset_sl_loosen" in space and "model:model:allow_ruleset_sl_loosen" not in space
    backtest_cfg = {
        "backtest_id": "sl", "start_date": "2024-01-01", "end_date": "2024-02-01",
        "enabled_instruments": ["AAA"], "experts": [{"class": "FMPRating", "settings": {}}],
        "initial_capital": 20_000.0, "account_settings": {}, "warmup_days": 0, "seed": 1,
    }
    for raw, expected in ((1, True), (0, False)):
        decoded = decode_params(strategy, {"model:allow_ruleset_sl_loosen": raw})
        assert decoded["expert_overrides"]["allow_ruleset_sl_loosen"] == raw
        trial = _build_daily_trial_config(backtest_cfg, decoded, None, option_trade_records=False)
        assert coerce_bool(trial["experts"][0]["settings"]["allow_ruleset_sl_loosen"]) is expected
