"""Add parent_order_id field to TradingOrder

Revision ID: 10fda7ae4bf3
Revises: 4b4da307fef4
Create Date: 2025-11-06 17:35:02.808784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fda7ae4bf3'
down_revision: Union[str, Sequence[str], None] = '4b4da307fef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradingorder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legs_broker_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('parent_order_id', sa.Integer(), nullable=True))
        batch_op.alter_column('order_type',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('MARKET', 'BUY_LIMIT', 'SELL_LIMIT', 'BUY_STOP', 'SELL_STOP', 'BUY_STOP_LIMIT', 'SELL_STOP_LIMIT', 'TRAILING_STOP', 'OCO', 'OTO', name='ordertype'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_tradingorder_parent_order_id', 'tradingorder', ['parent_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradingorder', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tradingorder_parent_order_id', type_='foreignkey')
        batch_op.alter_column('order_type',
               existing_type=sa.Enum('MARKET', 'BUY_LIMIT', 'SELL_LIMIT', 'BUY_STOP', 'SELL_STOP', 'BUY_STOP_LIMIT', 'SELL_STOP_LIMIT', 'TRAILING_STOP', 'OCO', 'OTO', name='ordertype'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
        batch_op.drop_column('parent_order_id')
        batch_op.drop_column('legs_broker_ids')

    # ### end Alembic commands ###
