"""add_data_field_to_expertrecommendation

Revision ID: 4bfccb7e5f31
Revises: e02b7075ca96
Create Date: 2025-10-22 11:47:36.130964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfccb7e5f31'
down_revision: Union[str, Sequence[str], None] = 'e02b7075ca96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expertrecommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.drop_column('trader_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expertrecommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trader_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
