"""Remove redundant date field from MarketAnalysis model

Revision ID: 86ba370fd69d
Revises: fe4892ad6036
Create Date: 2025-09-24 15:43:00.365159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ba370fd69d'
down_revision: Union[str, Sequence[str], None] = 'fe4892ad6036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the date column from marketanalysis - other changes are not needed for this migration
    with op.batch_alter_table('marketanalysis', schema=None) as batch_op:
        batch_op.drop_column('date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the date column to marketanalysis
    with op.batch_alter_table('marketanalysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
