"""allow_null_instrument_company_name

Revision ID: 9499764147b9
Revises: 97ecdd6d06d5
Create Date: 2025-10-08 18:24:27.468558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9499764147b9'
down_revision: Union[str, Sequence[str], None] = '97ecdd6d06d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('instrument_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.alter_column('instrument_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
