"""add risk_manager_run — per-symbol decisions for the classic/options risk managers

Revision ID: b7f3d21c98ae
Revises: c4d7e2b18a93
Create Date: 2026-08-31

The smart (agentic) risk manager has ``smartriskmanagerjob``; the classic and option
managers had nothing comparable. The classic manager wrote an ``ActivityLog`` row
carrying only counts ("reviewed 42, updated 7"), which answers "how many" and never
"which, and why not" — so the one question actually asked of it could only be answered
from the process log, and only until that rotated.

WHY ``decisions`` IS A JSON COLUMN AND NOT A CHILD TABLE. The rows are read as a set,
always for one run, and never aggregated across runs — the UI opens a single run and
lists it. A child table would cost one INSERT per symbol per run (a 200-symbol screener
universe run daily is ~73k rows/expert/year) to serve a query nothing makes. This
mirrors ``smartriskmanagerjob.graph_state``, which stores its own actions_log the same
way for the same reason.

``mode`` is a real column rather than a key inside the JSON because it is what the UI
filters on, and filtering on a JSON extract would need a scan.

Written by hand rather than autogenerated: the live database is behind head
(``alembic_version`` = d5e1b9a3c842 against a c4d7e2b18a93 head), so
``--autogenerate`` refuses, and upgrading a live trading database purely to emit a
revision is not a trade worth making.

Index names are the ones SQLAlchemy itself emits for these fields
(``ix_<table>_<column>``), so ``init_db()``'s create_all on a fresh database and Alembic
on an existing one produce the same schema. Foreign keys are declarative only — the live
DB runs with ``PRAGMA foreign_keys = 0``.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'b7f3d21c98ae'
down_revision: Union[str, Sequence[str], None] = 'c4d7e2b18a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "risk_manager_run"


def _create_table_if_absent(table_name: str, *columns) -> None:
    """``op.create_table`` unless the table is already there.

    A developer database that ``init_db()`` built with ``create_all`` on a checkout that
    already had the model will have the table without ever running this revision.

    A FRESH inspector every call, deliberately: an Inspector memoises its reflection.
    """
    if sa.inspect(op.get_bind()).has_table(table_name):
        # print(), not logger: alembic's fileConfig can disable the app loggers, and an
        # operator following the runbook needs to see what was skipped.
        print(f"[risk-manager-run] {table_name} already exists -- skipped")
        return
    op.create_table(table_name, *columns)


def _create_index_if_absent(index_name: str, table_name: str, columns) -> None:
    bind = op.get_bind()
    if not sa.inspect(bind).has_table(table_name):
        print(f"[risk-manager-run] {table_name} absent -- index {index_name} skipped")
        return
    existing = {ix["name"] for ix in sa.inspect(bind).get_indexes(table_name)}
    if index_name in existing:
        print(f"[risk-manager-run] index {index_name} already exists -- skipped")
        return
    op.create_index(index_name, table_name, columns, unique=False)


def upgrade() -> None:
    _create_table_if_absent(
        _TABLE,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expert_instance_id", sa.Integer(), nullable=False),
        # NULLABLE: the expert is what the run belongs to; the account is context, and a
        # run whose expert has no resolvable account is still a run worth keeping.
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("run_date", sa.DateTime(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        # Denormalised off `decisions` so the table view needs no JSON parsing to sort or
        # to show "7 of 42". NOT NULL: a recorded run always counted what it received,
        # even when that was nothing.
        sa.Column("symbols_received", sa.Integer(), nullable=False),
        sa.Column("symbols_funded", sa.Integer(), nullable=False),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["expert_instance_id"], ["expertinstance.id"],
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["account_id"], ["accountdefinition.id"],
                                ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_index_if_absent(f"ix_{_TABLE}_expert_instance_id", _TABLE,
                            ["expert_instance_id"])
    _create_index_if_absent(f"ix_{_TABLE}_account_id", _TABLE, ["account_id"])
    _create_index_if_absent(f"ix_{_TABLE}_run_date", _TABLE, ["run_date"])
    _create_index_if_absent(f"ix_{_TABLE}_mode", _TABLE, ["mode"])


def downgrade() -> None:
    if sa.inspect(op.get_bind()).has_table(_TABLE):
        op.drop_table(_TABLE)
