"""Add order_index to RulesetEventActionLink

Revision ID: c2379c5688f2
Revises: db671057a6b9
Create Date: 2025-09-26 21:50:07.886314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2379c5688f2'
down_revision: Union[str, Sequence[str], None] = 'db671057a6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite compatibility: Only add the order_index column
    op.add_column('ruleset_eventaction_link', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite compatibility: Only remove the order_index column
    op.drop_column('ruleset_eventaction_link', 'order_index')
    # ### end Alembic commands ###
