"""Proof: the 2026-09-29 split-basis-ack sweep clears ``mixed_basis`` on the CURRENT cached FMP
daily files (operator decision: 44 volatile symbols' offending moves are real price gaps, "leave
them through" -- see ``split_basis_overrides.py``'s "split-basis-ack sweep" block and
``tools/split_basis_ack_from_build.py``'s module docstring for how the entries were generated).

Re-runs the split-basis check the same way the warmup preflight's plan step does
(``ba2_providers.market_conditions.warmup._split_checks_for``): the cached bars, the symbol's
FMP split calendar, and the file's own full-fetch marker, fed to
``ba2_common.core.split_basis.check_split_basis``. The split calendar is read directly from the
disk-cached JSON payload (the same bytes ``FMPWarmupSource.split_calendar`` reads) rather than
through that class, so this module stays a ``ba2_common``-only test (no ``ba2_providers``
dependency, no network, no age check).

Reads this machine's real cache under ``ba2_common.config.CACHE_FOLDER``; every case is SKIPPED
when that symbol's cache files are absent (CI has none).
"""
from __future__ import annotations

import json
import os
from datetime import date
from typing import List

import pytest

import ba2_common.config as cfg
from ba2_common.core.market_condition_source import fmp_daily_cache_path, read_fmp_daily_cache
from ba2_common.core.split_basis import (
    REFETCH_VERDICTS,
    CalendarSplit,
    SplitBasisCheck,
    check_split_basis,
    read_full_fetch_marker,
)

#: The 6 symbols another (unmerged) branch already covers with its own ThetaData-verified
#: entries, copied verbatim into split_basis_overrides.py (see its "copied verbatim from
#: data/stage2-universe-repair b38ca1f5" block). This sweep's own generator
#: (tools/split_basis_ack_from_build.py) deliberately excludes them so as not to
#: duplicate/diverge from that measurement.
COPIED_FROM_OTHER_BRANCH = ("AMC", "ARWR", "ENLT", "FCEL", "MARA", "SMCI")

#: The 2026-09-29 sweep's own 38 symbols (acknowledge_jump entries generated by
#: tools/split_basis_ack_from_build.py from the goal2027atr equity market-condition build log).
SWEEP_38 = (
    "ABTC", "ACB", "AMWL", "BLNK", "BMNR", "BNED", "CBUS", "CLDX", "DRIO", "FIZZ", "FRMM", "GEVO",
    "GIBO", "GOAI", "GPUS", "GREE", "GYRE", "IOVA", "LAC", "LYEL", "MAAS", "NKTR", "NRXP", "OCGN",
    "ONDS", "OTLY", "PTN", "QUBT", "QXO", "RGC", "SBET", "SEZL", "SLGL", "SRPT", "TLRY", "TONX",
    "UP", "VRDN",
)

ACKNOWLEDGED = SWEEP_38 + COPIED_FROM_OTHER_BRANCH

#: Deliberately left refused -- IAC's verdicts are drift/undetectable (spin-off related, not a
#: real one-day gap), a kind acknowledge_jump cannot express. See
#: tools/split_basis_ack_from_build.py's module docstring.
STILL_REFUSES = ("IAC",)

#: Known leftovers: a symbol/date whose verdict is still a REFETCH_VERDICTS entry after
#: acknowledging its jump(s), because the underlying calendar split ITSELF (not the jump) still
#: fails the ratio rule with no marker to cover it. Measured empty on 2026-09-29 for all 44
#: acknowledged symbols on this machine's cache (every split of every one of them is either
#: "consistent" or "refetched" once its jump is acknowledged) -- kept as an explicit, documented
#: escape hatch rather than a silent pass: a future re-fetch that changes this must show up here,
#: named, not vanish into a blanket "allow failures" flag.
KNOWN_LEFTOVERS = {}

CACHE_ROOT = cfg.CACHE_FOLDER


def _daily_path(symbol: str):
    return fmp_daily_cache_path(symbol, CACHE_ROOT)


def _calendar_path(symbol: str) -> str:
    return os.path.join(CACHE_ROOT, "fmp_history", f"mc_stock_split__{symbol}.json")


def _has_cache(symbol: str) -> bool:
    path = _daily_path(symbol)
    return bool(path) and os.path.exists(path) and os.path.exists(_calendar_path(symbol))


def _local_split_calendar(symbol: str) -> List[CalendarSplit]:
    """``symbol``'s FMP split calendar from the disk-cached JSON payload, parsed directly (the
    same shape ``ba2_providers.symbol_info.parse_splits`` produces, ratio-less rows dropped)."""
    with open(_calendar_path(symbol), "r", encoding="utf-8") as f:
        payload = json.load(f)
    out: List[CalendarSplit] = []
    for row in payload.get("historical", []):
        d, num, den = row.get("date"), row.get("numerator"), row.get("denominator")
        if d is None or num is None or not den:
            continue
        out.append(CalendarSplit(date.fromisoformat(d), float(num) / float(den)))
    return out


def _checks_for(symbol: str) -> List[SplitBasisCheck]:
    """Mirrors ``warmup.py``'s ``_split_checks_for``: cached bars + calendar + the file's own
    full-fetch marker, through ``check_split_basis`` (which honours the shipped
    ``acknowledge_jump`` entries for ``symbol`` by default)."""
    path = _daily_path(symbol)
    dates, o, h, l, c, _v = read_fmp_daily_cache(path)
    return check_split_basis(dates, o, h, l, c, _local_split_calendar(symbol), symbol=symbol,
                             marker=read_full_fetch_marker(path))


@pytest.mark.parametrize("symbol", ACKNOWLEDGED)
def test_acknowledged_symbols_clear_the_refetch_verdicts(symbol):
    if not _has_cache(symbol):
        pytest.skip(f"no local FMP daily/split-calendar cache for {symbol} (CI has none)")
    checks = _checks_for(symbol)
    bad = [c for c in checks if c.verdict in REFETCH_VERDICTS]
    allowed_dates = KNOWN_LEFTOVERS.get(symbol, ())
    unexplained = [c for c in bad if c.split_date.isoformat() not in allowed_dates]
    assert not unexplained, f"{symbol} still refuses: {[c.to_dict() for c in unexplained]}"
    if bad:
        # A documented leftover is still visible in the run, not silently swallowed.
        print(f"{symbol}: known leftover(s) {[c.to_dict() for c in bad]}")


@pytest.mark.parametrize("symbol", STILL_REFUSES)
def test_symbols_left_unacknowledged_still_refuse(symbol):
    if not _has_cache(symbol):
        pytest.skip(f"no local FMP daily/split-calendar cache for {symbol} (CI has none)")
    checks = _checks_for(symbol)
    bad = [c for c in checks if c.verdict in REFETCH_VERDICTS]
    assert bad, (f"{symbol} was expected to still refuse (drift/undetectable, spin-off related, "
                f"deliberately not acknowledged) but is clean: {[c.to_dict() for c in checks]}")
    assert all(c.verdict != "mixed_basis" for c in bad), (
        f"{symbol} refuses on mixed_basis, which acknowledge_jump COULD have fixed: "
        f"{[c.to_dict() for c in bad]}")
