"""Operator-maintained corrections to the vendor split calendar (BT/live option parity, Part G1b).

WHY. ``split_basis.resolve_symbol_split_basis`` builds the adjusted -> as-traded factor from
FMP's split calendar. The 2026-09-23 sweep (97 symbols, 2020-2025, put-call-parity spot of the
nearest expiry vs the converted FMP close) found price adjustments FMP applies to its daily
closes but never lists in that calendar:

  * spin-offs: HON (Solstice, ex 2025-10-30, x1.0614), NVS (Sandoz, ex 2023-10-04, x1.0575);
  * quarterly stock dividends: SCCO, six of them 2024-08..2025-11 (x1.0057..x1.0101).

A spin-off of ~5% is not provable from prices (it is the size of an ordinary day), so these
cannot be detected by ``check_split_basis``; they are MEASURED once (the parity plateau step)
and recorded here with their evidence.

THE ENTRY KINDS

  * ``add_price_adjustment``  -- the FMP closes carry an adjustment of ``ratio`` at
    ``event_date`` that the calendar lacks: it joins the factor exactly like a calendar split
    (``day < event_date <= basis_date``). No jump proof is asked of it.
  * ``exclude_calendar_event`` -- a calendar row at ``event_date`` that the FMP closes do NOT
    carry: it is dropped from the factor (and its verdict from the proof). The row is matched
    by DATE only, so a calendar row whose ratio FMP does not state (``ratio=nan``, which
    ``resolve_symbol_split_basis`` would otherwise refuse inside the file's range) can be
    excluded too; the entry's own ``ratio`` is informational for this kind (the ratio of the
    row as measured, for the evidence) and is never applied.
  * ``acknowledge_jump`` -- a REAL one-day move (an earnings gap, not a basis defect) that
    sits within ``MIXED_BASIS_WINDOW_DAYS`` of a calendar split and so classifies it
    ``mixed_basis``. ``event_date`` is the jump's bar date and ``ratio`` its close / previous
    close. It removes ONLY that jump from the mixed-basis scan: the split stays in the factor
    and keeps whatever verdict the ratio rule gives it. The jump must still be in the file at
    that date with that ratio (+-``ANCHOR_TOLERANCE``), else it acknowledges nothing (and
    ``resolve_symbol_split_basis`` refuses the symbol, naming it). Honoured by every
    ``check_split_basis`` caller (the warmup preflight and the live drift report included), so
    an acknowledged jump also stops the warmup's re-fetch loop.

VALID ONLY FOR THE BYTES THEY WERE MEASURED ON. Every entry names ``anchors``: (date, FMP close)
pairs of the file it was measured against. A re-fetch that re-bases the history (FMP adding the
missing event itself, a new dividend adjustment) moves those closes, and the entry would then
double count or miss. So any anchor off by more than ``ANCHOR_TOLERANCE`` REFUSES the symbol
(``SplitBasisRefused``): re-measure, never guess.

VERSIONED. ``OVERRIDES_VERSION`` plus a digest of the symbol's own entries goes into
``SymbolSplitBasis.overrides_version`` and so into ``identity()`` and every cache key over
as-traded values. A symbol with no entry keeps ``overrides_version=None`` -- its identity is the
vendor calendar's, unchanged. Bump the version on any edit.

Data: ``docs/plans/2026-09-22-bt-live-option-parity.md`` Part G; the proposed JSON and sweep
evidence (``option_basis_overrides.proposed.json``, ``sessions_ratio_all.csv``).

THE 2026-09-29 SPLIT-BASIS-ACK SWEEP. The ``goal2027atr`` equity market-condition build (``tools
/warm_market_conditions.py build``, ``ohlcv-v1``) refused 44 volatile small/micro-cap symbols on
``mixed_basis``: every offending move was reviewed and is a real price gap (earnings, trial data,
a resignation...), operator decision 2026-09-29 "they are legit gaps, leave them through". 38 of
them are acknowledged below (their own block, generated by
``tools/split_basis_ack_from_build.py`` from the build log -- every ratio/anchor MEASURED from
the cached FMP daily file, never copied from the log text; re-run the generator against a fresh
build log to reproduce or extend the set). The other 6 (AMC, ARWR, ENLT, FCEL, MARA, SMCI) are
covered by a separate, unmerged branch's own ThetaData-verified entries, copied verbatim into
their own block instead of re-measured here. IAC is deliberately NOT acknowledged: its verdicts
are drift/undetectable (spin-off related), not mixed_basis -- a kind acknowledge_jump cannot
express; see ``tools/split_basis_ack_from_build.py``'s module docstring.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import date
from typing import Optional, Tuple

__all__ = [
    "OVERRIDES_VERSION",
    "ANCHOR_TOLERANCE",
    "KIND_ADD_PRICE_ADJUSTMENT",
    "KIND_EXCLUDE_CALENDAR_EVENT",
    "KIND_ACKNOWLEDGE_JUMP",
    "BasisOverride",
    "acknowledged_jumps",
    "BASIS_OVERRIDES",
    "overrides_for",
    "overrides_version_for",
]

OVERRIDES_VERSION = "2026-09-29.1"

#: An anchor close may differ from the recorded one by at most this fraction (0.1%).
ANCHOR_TOLERANCE = 0.001

KIND_ADD_PRICE_ADJUSTMENT = "add_price_adjustment"
KIND_EXCLUDE_CALENDAR_EVENT = "exclude_calendar_event"
KIND_ACKNOWLEDGE_JUMP = "acknowledge_jump"
_KINDS = (KIND_ADD_PRICE_ADJUSTMENT, KIND_EXCLUDE_CALENDAR_EVENT, KIND_ACKNOWLEDGE_JUMP)


@dataclass(frozen=True)
class BasisOverride:
    symbol: str
    event_date: date
    #: As a calendar ratio: the factor multiplies an adjusted close of a day before
    #: ``event_date`` into the as-traded basis (a spin-off worth 5.75% of the parent -> 1.0575).
    ratio: float
    kind: str
    #: ((date, fmp_close), ...) of the FMP daily file the entry was measured on.
    anchors: Tuple[Tuple[date, float], ...]
    evidence: str

    def __post_init__(self):
        if self.kind not in _KINDS:
            raise ValueError(f"{self.symbol} {self.event_date}: unknown override kind {self.kind!r}")
        if not (self.ratio > 0):
            raise ValueError(f"{self.symbol} {self.event_date}: ratio must be > 0")
        if not self.anchors:
            raise ValueError(f"{self.symbol} {self.event_date}: an override needs >= 1 anchor")

    def key(self) -> tuple:
        return (self.symbol.upper(), self.event_date.isoformat(), float(self.ratio), self.kind,
                tuple((d.isoformat(), float(c)) for d, c in self.anchors))


_A2020 = date(2020, 1, 2)
#: The 2026-09-29 split-basis-ack sweep (module: tools/split_basis_ack_from_build.py). Every
#: entry using this evidence was MEASURED (not copied) from the cached FMP daily file: ratio =
#: that bar's close / previous close, anchors = the (date, close) of both bars.
_SWEEP_EVIDENCE = (
    "operator 2026-09-29: accepted as a real price gap (volatile name; flagged mixed_basis by "
    "the goal2027atr equity market-condition build); not verified against a second source")
_SCCO_EVIDENCE = (
    "quarterly stock dividend in FMP prices, absent from the FMP split calendar; exact ex-date "
    "and ratio measured 2026-09-23 from ThetaData as-traded close vs FMP close (each step "
    "coincides with an FMP cash-dividend ex-date); data in scratchpad/g4/scco_theta_eod.csv, "
    "scco_fmp_raw.json")

BASIS_OVERRIDES: Tuple[BasisOverride, ...] = (
    BasisOverride(
        "HON", date(2025, 10, 30), 1.0614, KIND_ADD_PRICE_ADJUSTMENT, ((_A2020, 178.71),),
        "Solstice spin-off ex-date; in FMP prices (2026-09-16 refetch), not in the calendar. "
        "Parity/FMP 1.0616 before / 1.0003 after. The calendar row 2026-06-28 1907/2000 IS in "
        "the prices and stays. Residual after fix: median 1.0001, 0 sessions > 2%."),
    BasisOverride(
        "NVS", date(2023, 10, 4), 1.0575, KIND_ADD_PRICE_ADJUSTMENT, ((_A2020, 89.85),),
        "Sandoz spin-off ex-date; FMP prices adjusted, FMP split calendar has no row. "
        "Parity/FMP median 1.0604 (20 sessions before) vs 1.0028 (20 after); 2020-2023 plateau "
        "1.057-1.059. Residual after fix: median 1.0006, 0 sessions > 5%."),
    BasisOverride("SCCO", date(2024, 8, 9), 1.0057, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE),
    BasisOverride("SCCO", date(2024, 11, 6), 1.0062, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE),
    BasisOverride("SCCO", date(2025, 2, 11), 1.0073, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE),
    BasisOverride("SCCO", date(2025, 5, 2), 1.0098, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE),
    BasisOverride("SCCO", date(2025, 8, 15), 1.0101, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE),
    BasisOverride("SCCO", date(2025, 11, 12), 1.0085, KIND_ADD_PRICE_ADJUSTMENT,
                  ((_A2020, 40.18),), _SCCO_EVIDENCE + ". FMP closes 2025-10-20..2025-11-11 "
                  "already carry this adjustment (16 sessions ~0.85% off after the fix, below "
                  "the 5% guard tolerance); accepted"),

    # ---- copied verbatim from data/stage2-universe-repair b38ca1f5 (ThetaData-verified); keep
    # identical. AMC/ARWR/ENLT/FCEL/MARA/SMCI are covered by that branch's own measurement (a
    # wider mixed-basis window + ThetaData cross-check); the 2026-09-29 split-basis-ack sweep
    # (below) deliberately excludes these 6 symbols so as not to duplicate/diverge from them. ----
    BasisOverride(
        "AMC", date(2022, 8, 22), 2.0, KIND_EXCLUDE_CALENDAR_EVENT, ((_A2020, 74.6),),
        "The 2022-08-22 x2 row is the APE preferred-unit dividend: OCC left strikes alone and "
        "FMP's closes never took it. par/close 0.0998 over 2020-01..2022-08-19 (628 sessions) "
        "and 0.0986 over 2022-08-23..2023-08-23 = the 2023-08-24 1:10 row alone (kept)."),
    BasisOverride(
        "AMC", date(2023, 8, 14), 0.644487, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 74.6),),
        "Real move: -36% the day the court cleared the APE conversion (10 days before the "
        "1:10 reverse split), in a full re-fetch."),
    BasisOverride(
        "AMC", date(2023, 9, 6), 0.631965, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 74.6),),
        "Real move: -37% on the at-the-market offering announcement (13 days after the 1:10); "
        "par/close 1.0016 over 2023-08-25..2025-12-31, so the file is on one basis."),
    BasisOverride(
        "ARWR", date(2011, 11, 10), 1.401869, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 63.12),),
        "Real +40% move 7 days before the 2011-11-17 1:10 reverse split, in a full re-fetch; "
        "outside 2020-2025, guard clean (0 sessions > 5%)."),
    BasisOverride(
        "ENLT", date(2023, 2, 10), 0.682692, KIND_ACKNOWLEDGE_JUMP, ((date(2023, 2, 10), 17.75),),
        "The US IPO day: FMP's 27 bars before it (2023-01-03..02-09) are thin pre-listing "
        "prints (volume 0-350, flat 26.0 for two weeks), 11 days after the 2023-01-30 1:10 "
        "row. Not a basis change: the chain starts 2023-08-09 and is guard clean."),
    BasisOverride(
        "FCEL", date(2019, 6, 5), 0.666667, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 60.3),),
        "Real -33% move 27 days after the 2019-05-09 1:12 reverse split, in a full re-fetch."),
    BasisOverride(
        "FCEL", date(2024, 11, 11), 1 / 30, KIND_ADD_PRICE_ADJUSTMENT, ((_A2020, 60.3),),
        "1:30 reverse split effective 2024-11-11 (chain strike ladder 0.5-7 on 11-08, 1-12 from "
        "11-12; no ThetaData row on 11-11); in FMP prices, missing from the calendar. A fixed-"
        "ratio action: the NOMINAL 1/30 (the plateau convention measures 0.033532 = r 0.0334 "
        "before / 0.9949 after, the difference being borrow). Residual median 1.0000 over "
        "2020-01..2024-11-08 (878 sessions), 0.9973 after."),
    BasisOverride(
        "MARA", date(2017, 11, 22), 1.535211, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 1.05),),
        "Real Nov-2017 crypto spike (+54% / +173% / -41%) 23-29 days after the 2017-10-30 "
        "1:4 reverse split, in a full re-fetch; outside 2020-2025."),
    BasisOverride("MARA", date(2017, 11, 24), 2.729358, KIND_ACKNOWLEDGE_JUMP,
                  ((_A2020, 1.05),), "See the 2017-11-22 entry."),
    BasisOverride("MARA", date(2017, 11, 28), 0.591398, KIND_ACKNOWLEDGE_JUMP,
                  ((_A2020, 1.05),), "See the 2017-11-22 entry."),
    BasisOverride(
        "MARA", date(2019, 4, 10), 1.424354, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 1.05),),
        "Real +42% move 2 days after the 2019-04-08 1:4 reverse split, in a full re-fetch."),
    BasisOverride(
        "SMCI", date(2024, 10, 30), 0.673249, KIND_ACKNOWLEDGE_JUMP, ((_A2020, 2.36),),
        "Real -33% move (auditor resignation) 29 days after the 2024-10-01 10:1 split, in a "
        "full re-fetch; guard clean in 2020-2025."),

    # ---- split-basis-ack sweep, 2026-09-29 (operator decision, 44-symbol build report; IAC and
    # the 6 symbols above excluded -- see split_basis_ack_from_build.py's module docstring).
    # 38 symbols, 110 acknowledge_jump entries. Every ratio/anchor was MEASURED from the cached
    # FMP daily file (not copied from the build log), by
    # ``python tools/split_basis_ack_from_build.py <build.out> --exclude AMC,ARWR,ENLT,FCEL,MARA,SMCI``.
    # Evidence for every entry below: "operator 2026-09-29: accepted as a real price gap
    # (volatile name; flagged mixed_basis by the goal2027atr equity market-condition build); not
    # verified against a second source". ------------------------------------------------------
    BasisOverride(
        "ABTC", date(2024, 2, 13), 0.6601466992665037, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 2, 12), 306.75), (date(2024, 2, 13), 202.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "ABTC", date(2025, 8, 28), 1.421487603305785, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 8, 27), 90.75), (date(2025, 8, 28), 129.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "ACB", date(2020, 5, 15), 1.686746987951807, KIND_ACKNOWLEDGE_JUMP,
        ((date(2020, 5, 14), 66.4), (date(2020, 5, 15), 112.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "ACB", date(2020, 5, 18), 1.5267857142857142, KIND_ACKNOWLEDGE_JUMP,
        ((date(2020, 5, 15), 112.0), (date(2020, 5, 18), 171.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "AMWL", date(2024, 8, 1), 1.4019975031210987, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 7, 31), 8.01), (date(2024, 8, 1), 11.23)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BLNK", date(2017, 8, 30), 0.6914285714285714, KIND_ACKNOWLEDGE_JUMP,
        ((date(2017, 8, 29), 17.5), (date(2017, 8, 30), 12.1)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2012, 2, 6), 1.8181818181818181, KIND_ACKNOWLEDGE_JUMP,
        ((date(2011, 9, 27), 27.5), (date(2012, 2, 6), 50.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2012, 2, 23), 3.8, KIND_ACKNOWLEDGE_JUMP,
        ((date(2012, 2, 22), 50.0), (date(2012, 2, 23), 190.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2012, 3, 20), 5.4, KIND_ACKNOWLEDGE_JUMP,
        ((date(2012, 2, 24), 100.0), (date(2012, 3, 20), 540.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 3, 30), 1.7026666666666668, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 3, 29), 150.0), (date(2021, 3, 30), 255.4)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 3, 31), 0.5951448707909162, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 3, 30), 255.4), (date(2021, 3, 31), 152.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 4, 1), 1.5723684210526316, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 3, 31), 152.0), (date(2021, 4, 1), 239.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 4, 26), 1.6445623342175064, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 4, 22), 150.8), (date(2021, 4, 26), 248.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 4, 30), 0.32786885245901637, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 4, 29), 61.0), (date(2021, 4, 30), 20.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 3), 0.51, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 4, 30), 20.0), (date(2021, 5, 3), 10.2)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 4), 1.4215686274509804, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 3), 10.2), (date(2021, 5, 4), 14.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 10), 1.8758620689655172, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 6), 14.5), (date(2021, 5, 10), 27.2)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 11), 0.40441176470588236, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 10), 27.2), (date(2021, 5, 11), 11.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 12), 1.4545454545454546, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 11), 11.0), (date(2021, 5, 12), 16.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 18), 0.6, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 14), 20.0), (date(2021, 5, 18), 12.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 21), 1.6363636363636365, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 20), 11.0), (date(2021, 5, 21), 18.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2021, 5, 24), 0.5111111111111111, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 5, 21), 18.0), (date(2021, 5, 24), 9.2)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2025, 6, 4), 1.4074074074074074, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 3), 13.5), (date(2025, 6, 4), 19.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BMNR", date(2025, 6, 5), 0.40789473684210525, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 4), 19.0), (date(2025, 6, 5), 7.75)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 13), 0.6372077028885833, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 10), 29.08), (date(2024, 5, 13), 18.53)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 17), 2.526670409882089, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 16), 17.81), (date(2024, 5, 17), 45.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 20), 0.6888888888888889, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 17), 45.0), (date(2024, 5, 20), 31.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 21), 1.742258064516129, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 20), 31.0), (date(2024, 5, 21), 54.01)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 22), 2.092205147194964, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 21), 54.01), (date(2024, 5, 22), 113.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 23), 0.69929203539823, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 22), 113.0), (date(2024, 5, 23), 79.02)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 5, 31), 0.5870841487279843, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 5, 30), 76.65), (date(2024, 5, 31), 45.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 6, 7), 0.5337234370187866, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 6, 6), 32.47), (date(2024, 6, 7), 17.33)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "BNED", date(2024, 6, 11), 0.703731343283582, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 6, 10), 13.4), (date(2024, 6, 11), 9.43)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "CBUS", date(2023, 6, 13), 0.7073275862068966, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 6, 12), 23.2), (date(2023, 6, 13), 16.41)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "CLDX", date(2019, 2, 8), 0.6842105263157894, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 2, 7), 8.55), (date(2019, 2, 8), 5.85)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "DRIO", date(2019, 12, 3), 1.4910179640718564, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 12, 2), 100.2), (date(2019, 12, 3), 149.4)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "DRIO", date(2025, 9, 25), 1.427528675703858, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 9, 24), 9.59), (date(2025, 9, 25), 13.69)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "FIZZ", date(2021, 1, 27), 1.4016988416988418, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 1, 26), 64.75), (date(2021, 1, 27), 90.76)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "FRMM", date(2022, 12, 27), 1.5725806451612903, KIND_ACKNOWLEDGE_JUMP,
        ((date(2022, 12, 23), 235.6), (date(2022, 12, 27), 370.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "FRMM", date(2022, 12, 30), 1.7936507936507935, KIND_ACKNOWLEDGE_JUMP,
        ((date(2022, 12, 29), 359.1), (date(2022, 12, 30), 644.1)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "FRMM", date(2023, 1, 3), 1.5634218289085544, KIND_ACKNOWLEDGE_JUMP,
        ((date(2022, 12, 30), 644.1), (date(2023, 1, 3), 1007.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2015, 5, 7), 2.2285714285714286, KIND_ACKNOWLEDGE_JUMP,
        ((date(2015, 5, 6), 980.0), (date(2015, 5, 7), 2184.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2018, 6, 18), 3.618233618233618, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 15), 3.51), (date(2018, 6, 18), 12.7)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2018, 6, 19), 1.535433070866142, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 18), 12.7), (date(2018, 6, 19), 19.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2018, 6, 20), 0.6425641025641026, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 19), 19.5), (date(2018, 6, 20), 12.53)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2018, 6, 21), 0.6408619313647247, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 20), 12.53), (date(2018, 6, 21), 8.03)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GEVO", date(2018, 6, 29), 0.5928237129485179, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 28), 6.41), (date(2018, 6, 29), 3.8)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GIBO", date(2025, 7, 25), 1.5217391304347827, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 24), 230.0), (date(2025, 7, 25), 350.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GIBO", date(2025, 7, 29), 1.4179104477611941, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 28), 335.0), (date(2025, 7, 29), 475.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 9, 2), 2.2130816440235974, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 1), 5.404229), (date(2021, 9, 2), 11.96)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 9, 3), 0.2508361204013378, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 2), 11.96), (date(2021, 9, 3), 3.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 9, 7), 4.0, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 3), 3.0), (date(2021, 9, 7), 12.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 9, 9), 0.34629629629629627, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 8), 10.8), (date(2021, 9, 9), 3.74)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 9, 15), 2.1052631578947367, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 14), 3.8), (date(2021, 9, 15), 8.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2021, 10, 8), 0.42857142857142855, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 10, 7), 7.0), (date(2021, 10, 8), 3.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2025, 1, 16), 0.2604166666666667, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 1, 15), 11.52), (date(2025, 1, 16), 3.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2025, 1, 31), 2.84, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 1, 30), 3.0), (date(2025, 1, 31), 8.52)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GOAI", date(2025, 2, 10), 1.4084507042253522, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 2, 7), 8.52), (date(2025, 2, 10), 12.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GPUS", date(2019, 3, 29), 0.41088898329327755, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 3, 28), 25224816.0), (date(2019, 3, 29), 10364599.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GPUS", date(2019, 8, 19), 2.33009719200738, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 8, 16), 1837286.88), (date(2019, 8, 19), 4281057.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GPUS", date(2023, 7, 11), 0.7051285964047941, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 7, 10), 18348.88), (date(2023, 7, 11), 12938.32)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GPUS", date(2023, 7, 12), 1.6090906701952032, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 7, 11), 12938.32), (date(2023, 7, 12), 20818.93)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GREE", date(2021, 8, 26), 1.4111754578181248, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 8, 25), 1213.91), (date(2021, 8, 26), 1713.04)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GREE", date(2021, 9, 14), 0.6178027178526917, KIND_ACKNOWLEDGE_JUMP,
        ((date(2021, 9, 13), 1660.87), (date(2021, 9, 14), 1026.09)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GREE", date(2023, 6, 14), 1.5094339622641508, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 6, 13), 1.59), (date(2023, 6, 14), 2.4)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "GYRE", date(2015, 8, 20), 0.4343891402714932, KIND_ACKNOWLEDGE_JUMP,
        ((date(2015, 8, 19), 3480.75), (date(2015, 8, 20), 1512.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "IOVA", date(2013, 9, 3), 0.6666666666666666, KIND_ACKNOWLEDGE_JUMP,
        ((date(2013, 8, 30), 6.0), (date(2013, 9, 3), 4.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "LAC", date(2017, 11, 7), 1.6703056768558953, KIND_ACKNOWLEDGE_JUMP,
        ((date(2017, 11, 6), 4.58), (date(2017, 11, 7), 7.65)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "LYEL", date(2025, 6, 4), 1.6858573216520651, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 3), 7.99), (date(2025, 6, 4), 13.47)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "MAAS", date(2025, 4, 29), 1.5048899755501224, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 4, 28), 8.18), (date(2025, 4, 29), 12.31)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "MAAS", date(2025, 5, 1), 0.5109170305676856, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 4, 30), 11.45), (date(2025, 5, 1), 5.85)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "NKTR", date(2025, 6, 24), 2.5628930817610063, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 23), 9.54), (date(2025, 6, 24), 24.45)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "NRXP", date(2024, 3, 12), 0.6562032884902839, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 3, 11), 6.69), (date(2024, 3, 12), 4.39)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "OCGN", date(2019, 9, 27), 0.6923076923076924, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 9, 26), 14.04), (date(2019, 9, 27), 9.72)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "OCGN", date(2019, 10, 8), 0.6844919786096256, KIND_ACKNOWLEDGE_JUMP,
        ((date(2019, 10, 7), 1.87), (date(2019, 10, 8), 1.28)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "ONDS", date(2020, 12, 4), 0.4865506329113924, KIND_ACKNOWLEDGE_JUMP,
        ((date(2020, 12, 2), 12.64), (date(2020, 12, 4), 6.15)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "OTLY", date(2025, 2, 12), 0.658682634730539, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 2, 11), 11.69), (date(2025, 2, 12), 7.7)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "PTN", date(2025, 7, 23), 1.588235294117647, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 22), 8.5), (date(2025, 7, 23), 13.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "PTN", date(2025, 7, 24), 1.4074074074074074, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 23), 13.5), (date(2025, 7, 24), 19.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "PTN", date(2025, 7, 25), 0.6052631578947368, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 24), 19.0), (date(2025, 7, 25), 11.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "PTN", date(2025, 8, 6), 1.6666666666666667, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 8, 5), 7.5), (date(2025, 8, 6), 12.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "PTN", date(2025, 8, 18), 1.5765765765765767, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 8, 15), 5.55), (date(2025, 8, 18), 8.75)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QUBT", date(2018, 6, 4), 1.55, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 1), 4.0), (date(2018, 6, 4), 6.2)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QUBT", date(2018, 6, 27), 0.6333333333333333, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 6, 26), 6.0), (date(2018, 6, 27), 3.8)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QUBT", date(2018, 7, 6), 21.333333333333336, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 7, 5), 0.015), (date(2018, 7, 6), 0.32)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QUBT", date(2018, 7, 9), 2.0315625, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 7, 6), 0.32), (date(2018, 7, 9), 0.6501)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QUBT", date(2018, 7, 11), 5.815384615384615, KIND_ACKNOWLEDGE_JUMP,
        ((date(2018, 7, 10), 0.65), (date(2018, 7, 11), 3.78)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QXO", date(2015, 3, 4), 0.6333333333333333, KIND_ACKNOWLEDGE_JUMP,
        ((date(2015, 3, 3), 48.0), (date(2015, 3, 4), 30.4)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "QXO", date(2024, 6, 14), 0.6534079844206426, KIND_ACKNOWLEDGE_JUMP,
        ((date(2024, 6, 13), 205.4), (date(2024, 6, 14), 134.21)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "RGC", date(2025, 5, 29), 1.4254385964912282, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 5, 28), 13.68), (date(2025, 5, 29), 19.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "RGC", date(2025, 6, 20), 0.6, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 18), 63.35), (date(2025, 6, 20), 38.01)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "RGC", date(2025, 6, 23), 0.6235201262825573, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 6, 20), 38.01), (date(2025, 6, 23), 23.7)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "RGC", date(2025, 7, 2), 0.7095890410958904, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 1), 14.6), (date(2025, 7, 2), 10.36)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "RGC", date(2025, 7, 3), 2.219111969111969, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 7, 2), 10.36), (date(2025, 7, 3), 22.99)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SBET", date(2025, 5, 23), 1.7872340425531916, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 5, 22), 3.76), (date(2025, 5, 23), 6.72)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SBET", date(2025, 5, 27), 5.331845238095238, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 5, 23), 6.72), (date(2025, 5, 27), 35.83)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SBET", date(2025, 5, 29), 2.71639231824417, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 5, 28), 29.16), (date(2025, 5, 29), 79.21)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SEZL", date(2023, 4, 24), 0.5827727272727272, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 4, 21), 1.1), (date(2023, 4, 24), 0.64105)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SEZL", date(2023, 4, 27), 1.606738943920131, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 4, 26), 0.64105), (date(2023, 4, 27), 1.03)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SEZL", date(2023, 5, 9), 0.6591747572815534, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 5, 8), 1.03), (date(2023, 5, 9), 0.67895)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SEZL", date(2023, 5, 26), 0.290706796947436, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 5, 25), 0.70105), (date(2023, 5, 26), 0.2038)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SEZL", date(2023, 5, 30), 4.906771344455348, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 5, 26), 0.2038), (date(2023, 5, 30), 1.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SLGL", date(2025, 5, 6), 1.7330316742081449, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 5, 5), 4.42), (date(2025, 5, 6), 7.66)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "SRPT", date(2012, 7, 24), 2.4624277456647397, KIND_ACKNOWLEDGE_JUMP,
        ((date(2012, 7, 23), 3.46), (date(2012, 7, 24), 8.52)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "TLRY", date(2025, 12, 12), 1.4412811387900357, KIND_ACKNOWLEDGE_JUMP,
        ((date(2025, 12, 11), 8.43), (date(2025, 12, 12), 12.15)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "TONX", date(2023, 4, 18), 0.680327868852459, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 4, 17), 976.0), (date(2023, 4, 18), 664.0)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "UP", date(2023, 6, 22), 0.3961661341853035, KIND_ACKNOWLEDGE_JUMP,
        ((date(2023, 6, 21), 62.6), (date(2023, 6, 22), 24.8)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "VRDN", date(2016, 11, 9), 1.7549668874172186, KIND_ACKNOWLEDGE_JUMP,
        ((date(2016, 11, 8), 45.3), (date(2016, 11, 9), 79.5)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "VRDN", date(2016, 11, 18), 1.4053295932678822, KIND_ACKNOWLEDGE_JUMP,
        ((date(2016, 11, 17), 106.95), (date(2016, 11, 18), 150.3)),
        _SWEEP_EVIDENCE),
    BasisOverride(
        "VRDN", date(2020, 10, 28), 2.423076923076923, KIND_ACKNOWLEDGE_JUMP,
        ((date(2020, 10, 27), 7.8), (date(2020, 10, 28), 18.9)),
        _SWEEP_EVIDENCE),
)


def overrides_for(symbol: str, overrides: Optional[Tuple[BasisOverride, ...]] = None
                  ) -> Tuple[BasisOverride, ...]:
    """``symbol``'s entries (event-date order); ``overrides`` defaults to ``BASIS_OVERRIDES``."""
    src = BASIS_OVERRIDES if overrides is None else overrides
    s = str(symbol).upper()
    return tuple(sorted((o for o in src if o.symbol.upper() == s), key=lambda o: o.event_date))


def acknowledged_jumps(entries: Tuple[BasisOverride, ...]) -> dict:
    """``{jump_date: close_ratio}`` of the ``acknowledge_jump`` entries among ``entries``."""
    return {e.event_date: float(e.ratio) for e in entries if e.kind == KIND_ACKNOWLEDGE_JUMP}


def overrides_version_for(entries: Tuple[BasisOverride, ...],
                          version: Optional[str] = None) -> Optional[str]:
    """``"<OVERRIDES_VERSION>:<digest of the entries>"``, or None for no entries (the
    vendor calendar as-is, identity unchanged)."""
    if not entries:
        return None
    v = OVERRIDES_VERSION if version is None else version
    blob = repr(tuple(o.key() for o in entries)).encode("utf-8")
    return f"{v}:{hashlib.sha256(blob).hexdigest()[:12]}"
